IssueTracker/config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :invites
  resources :comments
  resources :issues
  root 'users#index'

  get 'signup' => 'users#new'
  resources:users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/project' => 'project#index'
  get '/project/new' => 'project#new'
  post '/project/new' => 'project#create'
  get '/project/:id/edit' => 'project#edit'
  post '/project/:id/edit' => 'project#update'
  get '/project/:id' => 'project#show', as: :id
  get 'project/:id/add' => 'project#add'
  get 'project/:id/remove/:rem' => 'project#remove'

  get '/project/:id/issue/new' => 'issues#new'
  post '/project/:id/issue/new' => 'issues#create', as: :project_id

  get 'issue/:id/comment/new' => 'comments#new'
  post 'issue/:id/comment/new' => 'comments#create', as: :issue_id
  get 'issue/:id/addtag' => 'tags#new'
  post 'issue/:id/addtag' => 'tags#create'
  get 'issue/:id/remtag/:tid' => 'issues#remtag'
  get 'issue/:id/close' => 'issues#close'
  get 'issue/:id/assign/:uid' => 'issues#assign'

  get 'issue/:id/add' => 'issues#voteadd'
  get 'issue/:id/rem' => 'issues#voterem'

  post 'invites/new' => 'invites#create'
  get '/invites/:id' => 'invites#add', as: :invite_id

end

IssueTracker/app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  has_many :comments
  has_many :votes

  has_one :assign
  has_many :tags
end

IssueTracker/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  def assign
    @issue = Issue.find(params[:id])
    @project = @issue.project

    if @issue.assign
      @issue.assign.destroy
    end
    Assign.create(user_id: params[:uid], issue_id: params[:id])
    Notification.create(user_id: params[:uid], notify: "You have been assigned a issue",link:issue_path(params[:id]))

    redirect_to "/issues/#{@issue.id}"
  end

  def close
    @issue = Issue.find(params[:id])
    @project = @issue.Project

    if !@project.private || @project.user.id == session[:user_id]
      @issue.update(open: true)
    end

    redirect_to "/issues/#{@issue.id}"
  end

  def remtag
    @tag = Tag.find(params[:tid])
    @issue = @tag.issue
    @project = @issue.project

    if !@project.private || @project.user.id == session[:user_id]
      @tag.destroy
    end
    redirect_to "/issues/#{params[:id]}"
  end

  def voteadd
    @issue = Issue.find(params[:id])
    @user = User.find(session[:user_id])
    @project = @issue.project

    if @project.working.detect{|p| p.user_id == @user.id} && !@user.votes.detect{|v| v.issue_id == @issue.id}
      Vote.create(user_id: session[:user_id], issue_id:params[:id])
    end

    redirect_to "/issues/#{@issue.id}"
  end

  def voterem
    @issue = Issue.find(params[:id])
    @user = User.find(session[:user_id])

    @vote = @user.votes.detect{|v| v.issue_id == @issue.id}
    if @vote
      @vote.destroy
    end
    redirect_to "/issues/#{@issue.id}"
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      @project = Project.find(params[:id])
      @project.issues << @issue
      if @issue.save
        @project.working.each do |w|
          @user = w.user
          Notification.create(user_id: @user.id, notify: "There is a new issue",link:issue_path(@issue.id))
        end
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }

        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:heading, :description, :status, :open, :dupl)
    end
end

IssueTracker/app/helpers/issues_helper.rb
module IssuesHelper
end

IssueTracker/app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
<table>
  <tr><td>Heading</td><td><%= f.text_field :heading %></td></tr>
  <tr><td>Description:</td><td><%= f.text_area :description %></td></tr>
  <tr><td>Status:</td><td><%= f.text_field :status %></td></tr>
  <tr><td>Open/Closed:</td><td><%= f.check_box :open %></td></tr>
  <tr><td>Duplicate:</td><td><%= f.check_box :dupl %></td></tr>
</table>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

IssueTracker/app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

IssueTracker/app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<script>
  document.getElementById("issue").setAttribute("class","active");
</script>



<br /><br />

    <div style="border:1px solid black; padding:1em;">
    <% @issues.each do |issue| %>
      <div>
      <div >
         <h3> <%= issue.heading %> (<%= Project.find(issue.project_id).name %>)</h3>
       </div>
         <p>
           <%= issue.description %>
           <% if issue.dupl %>Marked Dup <% end %>
         </p>
        <%= link_to 'Show', issue %>
        <%= link_to 'Edit', edit_issue_path(issue) %>
        <%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>


<br>

IssueTracker/app/views/issues/new.html.erb
<h1>New Issue</h1>


<%= form_for(:issue) do |f| %>
<table>
  <tr><td>Heading</td><td><%= f.text_field :heading %></td></tr>
  <tr><td>Description:</td><td><%= f.text_area :description %></td></tr>
  <tr><td>Status:</td><td><%= f.text_field :status %></td></tr>
  <tr><td>Open/Closed:</td><td><%= f.check_box :open %></td></tr>
  <tr><td>Duplicate:</td><td><%= f.check_box :dupl %></td></tr>
</table>
  <%= f.submit "Create New", class: "btn-submit" %>
<% end %>

IssueTracker/app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', id_path(Project.find(@issue.project_id)) %>
<%= link_to 'Destroy', @issue, method: :delete, data: { confirm: 'Are you sure?' } %>
<% if !@issue.votes.detect{|v| v.user_id == session[:user_id]} %>
<%= link_to 'Vote', "/issue/#{@issue.id}/add" %>
<% else %>
<%= link_to 'Unvote', "/issue/#{@issue.id}/rem" %>
<% end %>

<%= link_to 'New Comment', issue_id_path(@issue) %>
<br>
<% if ! @issue.open %>
<%= link_to 'Close This Issue', "/issue/#{@issue.id}/close" %>
<% else %>
Closed Issue
<% end %>
<h2><%= @issue.heading %></h2>
  <% if @issue.dupl %>Marked Duplicate <% end %>
<p>Votes:<%= @issue.votes.count %></p>
<p><%= @issue.description %></p>

<p> <b>Tags:</b>
  <% @tags = @issue.tags %>
  <% @tags.each do |tag| %>
  <%= tag.tag %>(<%= link_to "Remove", "/issue/#{@issue.id}/remtag/#{tag.id}" %>),
  <% end %>
  <br>
  <%= link_to "Add Tags", "/issue/#{@issue.id}/addtag" %>
</p>

<br>
<%if @issue.assign %>
<h5> Assigned To: <%= @issue.assign.user.first_name %> <%= @issue.assign.user.last_name %> </h5>
<% end %>
<h3> Comments </h3>
<% @comments = @issue.comments %>
    <div style="border:1px solid black; padding:1em;">
<% @comments.each do |comment| %>
<div style="margin:10px; ">

     <%= comment.comment %>

   <p>
   <b>Mentions:</b>
   <% @mentions = comment.mentions %>
   <% @mentions.each do |mention| %>
   <% if mention.user %>
   <%= mention.user.first_name %>
   <%= mention.user.last_name %>
   <% end %>
   <% end %>
   <br>
   <%= link_to 'Show', comment %>
   <%= link_to 'Edit', edit_comment_path(comment) %>
   <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
     </p>
</div>
<% end %>
</div>
<br>
<% @project = @issue.project %>
<% @workers = @issue.project.working %>
<div style = "border:1px solid black; padding:1em;">
  <% @workers.each do |w| %>
    <p>
      <%= w.user.first_name %> <%= w.user.last_name %>
      <% if @project.user_id == session[:user_id] && w.user.id != session[:user_id] %>
      <%= link_to "Remove", "/project/#{@project.id}/remove/#{w.user.id}" %>
      <% end %>
      <% if @project.user_id == session[:user_id] %>
      <%= link_to "Assign", "/issue/#{@issue.id}/assign/#{w.user.id}" %>
      <% end %>
    </p>
  <% end %>

</div>