IssueTracker/config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :invites
  resources :comments
  resources :issues
  root 'users#index'

  get 'signup' => 'users#new'
  resources:users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/project' => 'project#index'
  get '/project/new' => 'project#new'
  post '/project/new' => 'project#create'
  get '/project/:id/edit' => 'project#edit'
  post '/project/:id/edit' => 'project#update'
  get '/project/:id' => 'project#show', as: :id
  get 'project/:id/add' => 'project#add'
  get 'project/:id/remove/:rem' => 'project#remove'

  get '/project/:id/issue/new' => 'issues#new'
  post '/project/:id/issue/new' => 'issues#create', as: :project_id

  get 'issue/:id/comment/new' => 'comments#new'
  post 'issue/:id/comment/new' => 'comments#create', as: :issue_id
  get 'issue/:id/addtag' => 'tags#new'
  post 'issue/:id/addtag' => 'tags#create'
  get 'issue/:id/remtag/:tid' => 'issues#remtag'
  get 'issue/:id/close' => 'issues#close'
  get 'issue/:id/assign/:uid' => 'issues#assign'

  get 'issue/:id/add' => 'issues#voteadd'
  get 'issue/:id/rem' => 'issues#voterem'

  post 'invites/new' => 'invites#create'
  get '/invites/:id' => 'invites#add', as: :invite_id

end

IssueTracker/app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

IssueTracker/app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]

  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.all
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end

  # GET /invites/new
  def new
    @invite = Invite.new
  end

  # GET /invites/1/edit
  def edit
  end

  def add
    @invite = Invite.find(:invite_id)
    if @invite.user_id = session[:user_id]
      @invite.destroy
    end
  end

  # POST /invites
  # POST /invites.json
  def create
    @project = Project.find(params[:invite][:project_id])
    if @project.user_id == session[:user_id] && params[:invite][:user_id] != @project.user_id
      @invite = Invite.new(invite_params)

      respond_to do |format|
        if @invite.save
          format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
          format.json { render :show, status: :created, location: @invite }
        else
          format.html { render :new }
          format.json { render json: @invite.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    if @invite.project.user_id == session[:user_id]
      respond_to do |format|
        if @invite.update(invite_params)
          format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
          format.json { render :show, status: :ok, location: @invite }
        else
          format.html { render :edit }
          format.json { render json: @invite.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    if @invite.user_id == session[:user_id] || @invite.project.user_id == session[:user_id]
      @invite.destroy
      respond_to do |format|
        format.html { redirect_to invites_url, notice: 'Invite was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:user_id, :project_id)
    end
end

IssueTracker/app/helpers/invites_helper.rb
module InvitesHelper
end

IssueTracker/app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <table>
  <tr><td>Project_id:</td><td><%= f.text_field :project_id %></td></tr>
  <tr><td>Issue_id:</td><td><%= f.text_field :user_id %></td></tr>
</table>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

IssueTracker/app/views/invites/edit.html.erb
<h1>Editing Invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

IssueTracker/app/views/invites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invites</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invites.each do |invite| %>
      <tr>
        <td><%= link_to 'Show', invite %></td>
        <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
        <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invite', new_invite_path %>

IssueTracker/app/views/invites/new.html.erb
<h1>New Invite</h1>

<%= form_for(:invite) do |f| %>
<table>
<tr><td>Project_id:</td><td><%= f.text_field :project_id %></td></tr>
<tr><td>Issue_id:</td><td><%= f.text_field :user_id %></td></tr>
</table>
  <%= f.submit "Create New", class: "btn-submit" %>
<% end %>

<%= link_to 'Back', invites_path %>

IssueTracker/app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>