IssueTracker/config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :invites
  resources :comments
  resources :issues
  root 'users#index'

  get 'signup' => 'users#new'
  resources:users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/project' => 'project#index'
  get '/project/new' => 'project#new'
  post '/project/new' => 'project#create'
  get '/project/:id/edit' => 'project#edit'
  post '/project/:id/edit' => 'project#update'
  get '/project/:id' => 'project#show', as: :id
  get 'project/:id/add' => 'project#add'
  get 'project/:id/remove/:rem' => 'project#remove'

  get '/project/:id/issue/new' => 'issues#new'
  post '/project/:id/issue/new' => 'issues#create', as: :project_id

  get 'issue/:id/comment/new' => 'comments#new'
  post 'issue/:id/comment/new' => 'comments#create', as: :issue_id
  get 'issue/:id/addtag' => 'tags#new'
  post 'issue/:id/addtag' => 'tags#create'
  get 'issue/:id/remtag/:tid' => 'issues#remtag'
  get 'issue/:id/close' => 'issues#close'
  get 'issue/:id/assign/:uid' => 'issues#assign'

  get 'issue/:id/add' => 'issues#voteadd'
  get 'issue/:id/rem' => 'issues#voterem'

  post 'invites/new' => 'invites#create'
  get '/invites/:id' => 'invites#add', as: :invite_id

end

IssueTracker/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  
  has_many :issues
  has_many :working
  has_many :invite
end

IssueTracker/app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :require_user, only: [:index, :new, :show, :create]

  def index
    @user = User.find(session[:user_id])
    @projects = @user.projects
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])

    puts @project.working.detect{|p| p.id == session[:user_id] }
    if check(@project.id) == 0
      redirect_to '/'
    end

    @user = User.find(@project.user_id)
    @issues = @project.issues
    @workers = @project.working
  end

  def add
    @user = User.find(session[:user_id])
    @project = Project.find(params[:id])
    @invite = @user.invite.detect{|i| i.project_id == @project.id}

    if @invite
      @invite.destroy
      Working.create(user_id: @user.id, project_id: @project.id)
    else
      redirect_to "/"
    end
  end

  def remove
    @project = Project.find(params[:id])
    @user = User.find(params[:rem])

    @working = @project.working.detect{|p| p.user_id == @user.id}
    if @working && @project.user != @user
      @working.destroy
    end

    redirect_to "/project/#{@project.id}"
  end

  def create
    @project = Project.new(project_params)
    @user = User.find(session[:user_id])
    @user.projects << @project
    Working.create(user_id: @user.id, project_id: @project.id)
    if @project.save
      redirect_to '/'
    else
      redirect_to '/project/create'
    end
  end

  def update
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :description, :private)
  end

  def check(x)
    @project = Project.find(x)

    if @project.private == 0
      return 1
    end

    if @project.working.detect{|p| p.user_id == session[:user_id] }
      return 1
    else
      return 0
    end
  end
end

IssueTracker/app/helpers/project_helper.rb
module ProjectHelper
end

IssueTracker/app/views/project/_form.html.erb
<%= form_for(:project) do |f| %>
  <table>
  <tr><td>Name:</td><td><%= f.text_field :name %></td></tr>
  <tr><td>Description:</td><td><%= f.text_field :description %></td></tr>
  <tr><td>Private/Public:</td><td><%= f.check_box :private %></td></tr>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</table>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

IssueTracker/app/views/project/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', project_path %>

IssueTracker/app/views/project/index.html.erb
<div class="jumbotron">
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
</div>
<%= link_to "New Project", project_new_path() %>

<script>
  document.getElementById("project").setAttribute("class","active");
</script>


<h2>Your Projects</h2>

<div style="border:1px solid black; padding:1em">
<% @projects.each do |p| %>
  <div style="border:1px solid black; margin:1px">
      <h3 class="bg-primary" >
        <%= p.name %>
      </h3>
    <%= p.description %><br>
    <%= link_to "See More", id_path(p) %>
  </div>
<% end %>
</div>

IssueTracker/app/views/project/new.html.erb
<%= render 'form' %>

IssueTracker/app/views/project/show.html.erb
<div class="jumbotron">
  <h2>
    <%= @project.name %>
  </h2>
  Owner: <%= @project.user.first_name %> <%= @project.user.last_name %><br>
</div>
<%= @project.description %><br>

<%= link_to 'Edit', "/project/"+@project.id.to_s+"/edit" %> |
<%= link_to 'Back', project_path %> |

<%= link_to "New Issue", project_id_path(@project) %> |
<%= link_to "New Invite", new_invite_path() %>



<h3>Issues:-</h3>

Search for Title/description:<input type="text" id="searchbox" title="Search for Title/description"/><br>
Search for Person:<input type="text" id="personbox" title="Search for Person"/><br>
Search for Tags:<input type="text" id="tagbox" title="Search for Tags"/><br>

<button onclick="search()">Submit</button>

<div id="container" style = "border:1px solid black; padding:1em;">
  <b>Open Issues:</b>
  <% @issues.each do |issue| %>
    <% if issue.open==false %>
    <div style = "margin:10px;" class="issue" id="<%= issue.id %>">
      <h4 class="Title"><%= issue.heading %></h4>
      <p class="Description"><%= issue.description %></p>
      <p><%= issue.status %></p>
      <p><b>Tags:</b>
        <% @tags = issue.tags %>
        <% @tags.each do |tag| %>
        <%= tag.tag %>,
        <% end %>
      </p>
      <p><b>Assigned To:</b>
        <% if issue.assign %>
        <%= issue.assign.user.first_name %> <%= issue.assign.user.last_name %>
        <% end %>
      </p>
      <p><b>Mentions:</b>
        <% @comments = issue.comments %>
        <% @comments.each do |c| %>
        <% @mentions = c.mentions %>
        <% @mentions.each do |m| %>
        <% if m.user %>
        <% @user = m.user %>
        <%= @user.first_name %> <%= @user.last_name %>,
        <% end %>
        <% end %>
        <% end %>
      </p>

      <b> Open </b>
      <%= link_to "Look Into It", issue_path(issue) %>
    </div>
    <% end %>
  <% end %>

  <br>
  <b>Closed Issues:</b>
  <% @issues.each do |issue| %>
    <% if issue.open %>
    <div style = "margin:10px;" class="issue">
      <h4><%= issue.heading %></h4>
      <p><%= issue.description %></p>
      <p><%= issue.status %></p>
      <p><b>Tags:</b>
        <% @tags = issue.tags %>
        <% @tags.each do |tag| %>
        <%= tag.tag %>,
        <% end %>
      </p>
      <p><b>Assigned To:</b>
        <% if issue.assign %>
        <%= issue.assign.user.first_name %> <%= issue.assign.user.last_name %>
        <% end %>
      </p>
      <p><b>Mentions:</b>
        <% @comments = issue.comments %>
        <% @comments.each do |c| %>
        <% @mentions = c.mentions %>
        <% @mentions.each do |m| %>
        <% if m.user %>
        <% @user = m.user %>
        <%= @user.first_name %> <%= @user.last_name %>,
        <% end %>
        <% end %>
        <% end %>
      </p>
      <b>Closed</b>
      <%= link_to "Look Into It", issue_path(issue) %>
    </div>
    <% end %>
  <% end %>
</div>
<br>

<h3>People Working On it:-</h3>

<div style = "border:1px solid black; padding:1em;">
  <% @workers.each do |w| %>
    <p>
      <%= w.user.first_name %> <%= w.user.last_name %>
      <% if @project.user_id == session[:user_id] && w.user.id != session[:user_id] %>
      <%= link_to "Remove", "/project/#{@project.id}/remove/#{w.user.id}" %>
      <% end %>
    </p>
  <% end %>

</div>

<script>
Array.prototype.clean = function(deleteValue) {
  for (var i = 0; i < this.length; i++) {
    if (this[i] == deleteValue) {
      this.splice(i, 1);
      i--;
    }
  }
  return this;
};

var issues;
var Issues;

window.onload = function()
{
  issues = document.getElementsByClassName("issue");
  Issues = [];

  for (var i = 0; i<issues.length ; i++)
  {
      var issue = {
      content: issues[i].innerHTML,
      title: issues[i].childNodes[1].innerHTML,
      description: issues[i].childNodes[3].innerHTML,
      tags: issues[i].childNodes[7].childNodes[1].nodeValue.replace(/[\n\r]+/g, '').replace(/ /g,'').split(",").clean(""),
      assign: issues[i].childNodes[9].childNodes[1].nodeValue.replace(/[\n\r]+/g, '').replace(/ /g,''),
      mentions: issues[i].childNodes[11].childNodes[1].nodeValue.replace(/[\n\r]+/g, '').replace(/ /g,'').split(",").clean(""),
      }
      Issues.push(issue);
  }

}

function superbag(sup, sub) {
    sup.sort();
    sub.sort();
    var i, j;
    for (i=0,j=0; i<sup.length && j<sub.length;) {
        if (sup[i] < sub[j]) {
            ++i;
        } else if (sup[i] == sub[j]) {
            ++i; ++j;
        } else {
            // sub[j] not in sup, so sub not subbag
            return false;
        }
    }
    // make sure there are no elements left in sub
    return j == sub.length;
}

function search()
{
  var container = document.getElementById("container");

  var search = document.getElementById("searchbox").value;
  document.getElementById("searchbox").value=""

  var person = document.getElementById("personbox").value.replace(/ /g,'');
  document.getElementById("personbox").value=""

  var tags = document.getElementById("tagbox").value;
  document.getElementById("tagbox").value=""

  console.log(Issues)

  container.innerHTML = "";

  if(search)
  {
    console.log(search);
    for(var i=0; i<Issues.length; i++)
    {
      if (Issues[i].title.indexOf(search)>-1 || Issues[i].description.indexOf(search)>-1)
      {
        container.innerHTML += Issues[i].content
      }
    }
  }

  if(person)
  {
    console.log(person)
    for(var i=0; i<Issues.length; i++)
    {
      var flag =0 ;
      if (Issues[i].assign.indexOf(person)>-1)
      {
        container.innerHTML += Issues[i].content
        flag=1;
      }
      if(flag==0){
        for (var j=0; j<Issues[i].mentions.length; j++)
        {
          if(Issues[i].mentions[j].indexOf(person)>-1)
          {
            container.innerHTML += Issues[i].content
            flag=1;
          }
          if(flag)break;
        }
      }
    }
  }

  if(tags)
  {
    tags = tags.replace(/ /g,'').split(",").clean("");
    ids = []
    for(var tagid=0; tagid<tags.length; tagid++)
    {
      tag = tags[tagid];
      tag = tag.split("and").clean("");
      for(var i=0;i<Issues.length;i++)
      {
        var issue = Issues[i];
        if (superbag(issue.tags,tag))
        {
          ids.push(i);
        }
      }
    }
    uniqueArray = ids.filter(function(item, pos) {
      return ids.indexOf(item) == pos;
    })
    for(var i=0; i<uniqueArray.length; i++)
    {
      var issue = Issues[uniqueArray[i]];
      container.innerHTML+= issue.content
    }
  }


}
</script>