IssueTracker/config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :invites
  resources :comments
  resources :issues
  root 'users#index'

  get 'signup' => 'users#new'
  resources:users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/project' => 'project#index'
  get '/project/new' => 'project#new'
  post '/project/new' => 'project#create'
  get '/project/:id/edit' => 'project#edit'
  post '/project/:id/edit' => 'project#update'
  get '/project/:id' => 'project#show', as: :id
  get 'project/:id/add' => 'project#add'
  get 'project/:id/remove/:rem' => 'project#remove'

  get '/project/:id/issue/new' => 'issues#new'
  post '/project/:id/issue/new' => 'issues#create', as: :project_id

  get 'issue/:id/comment/new' => 'comments#new'
  post 'issue/:id/comment/new' => 'comments#create', as: :issue_id
  get 'issue/:id/addtag' => 'tags#new'
  post 'issue/:id/addtag' => 'tags#create'
  get 'issue/:id/remtag/:tid' => 'issues#remtag'
  get 'issue/:id/close' => 'issues#close'
  get 'issue/:id/assign/:uid' => 'issues#assign'

  get 'issue/:id/add' => 'issues#voteadd'
  get 'issue/:id/rem' => 'issues#voterem'

  post 'invites/new' => 'invites#create'
  get '/invites/:id' => 'invites#add', as: :invite_id

end

IssueTracker/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :issue
end

IssueTracker/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    @issue = Issue.find(params[:id])
    @issue.tags << @tag

    @project = @issue.project

    if !@project.private || @project.user.id == session[:user_id]
      @tag.destroy

    else
      respond_to do |format|
        if @tag.save
          format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
          format.json { render :show, status: :created, location: @tag }
        else
          format.html { render :new }
          format.json { render json: @tag.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tag)
    end
end

IssueTracker/app/helpers/tags_helper.rb
module TagsHelper
end

IssueTracker/app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <%= f.text_field :tag %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

IssueTracker/app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

IssueTracker/app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>
<script>
  document.getElementById("tag").setAttribute("class","active");
</script>


<%= link_to 'New Tag', new_tag_path %>

<h1>Listing Tags</h1>



<div style="border:1px solid black; padding:1em;">
<% @tags.each do |tag| %>
  <div>
  <div >
     <h3> <%= tag.id %>. <%= tag.tag %></h3>
   </div>
    <%= link_to 'Show', tag %>
    <%= link_to 'Edit', edit_tag_path(tag) %>
    <%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>
</div>

IssueTracker/app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= form_for(:tag) do |f| %>
  <%= f.text_field :tag, :placeholder => "Tag Name" %>
  <%= f.submit "Create New", class: "btn-submit" %>
<% end %>


<%= link_to 'Back', tags_path %>

IssueTracker/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @tag.tag %></h3>
<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', issue_path(@tag.issue)%>